/**
 * Kelompok 10
 * Kelas    : S1 IF-06-B
 * Anggota  :
 * 1. Naufal Yusuf Kartiko (181020)
 * 2. Nur Rizki Adi Prasetyo (18102064)
 * 3. Wisanti (181020)
 */
package com.nurrizkiadip;

import java.text.ParseException;
import javax.swing.JOptionPane;

public class Beranda extends javax.swing.JFrame {

    public Beranda() throws ParseException {
        if(Main.waktuSetLimit != null)
            Main.setUlangLimitBulanan();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuBeranda = new javax.swing.JMenuItem();
        menuCatat = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenuItem();
        menuPengaturan = new javax.swing.JMenuItem();
        MenuEdit = new javax.swing.JMenu();
        menuKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beranda Struk Harian");
        setMaximumSize(new java.awt.Dimension(0, 0));
        setSize(new java.awt.Dimension(600, 500));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELAMAT DATANG DI");

        jLabel2.setFont(new java.awt.Font("Nimbus Mono L", 1, 21)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("APLIKASI STRUK HARIAN");

        menuFile.setText("File");

        menuBeranda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/homeflat_converted2.png"))); // NOI18N
        menuBeranda.setText(" Beranda");
        menuBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBerandaActionPerformed(evt);
            }
        });
        menuFile.add(menuBeranda);

        menuCatat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuCatat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/document_write_converted.png"))); // NOI18N
        menuCatat.setText(" Catat Pengeluaran");
        menuCatat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCatatActionPerformed(evt);
            }
        });
        menuFile.add(menuCatat);

        menuLaporan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Laporan-converted2.png"))); // NOI18N
        menuLaporan.setText(" Laporan");
        menuLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanActionPerformed(evt);
            }
        });
        menuFile.add(menuLaporan);

        menuPengaturan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuPengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Setting-converted2.png"))); // NOI18N
        menuPengaturan.setText(" Pengaturan");
        menuPengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPengaturanActionPerformed(evt);
            }
        });
        menuFile.add(menuPengaturan);

        MenuBar.add(menuFile);

        MenuEdit.setText("Exit");

        menuKeluar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit-converted2.png"))); // NOI18N
        menuKeluar.setText(" Keluar");
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        MenuEdit.add(menuKeluar);

        MenuBar.add(MenuEdit);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //method tombol menu item keluar untuk mengakhiri running program
    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuKeluarActionPerformed

    //method tombol menu item laporan untuk menampilkan laporan perbelanjaan
    private void menuLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanActionPerformed
        // TODO add your handling code here:
        Laporan lap = null;
        try {
            lap = new Laporan();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Error : " + ex.getMessage());
        }
        Beranda.this.setVisible(false);
        lap.setVisible(true);
    }//GEN-LAST:event_menuLaporanActionPerformed

    //menu item catat perbelanjaan untuk menambahkan riwayat perbelanjaan
    private void menuCatatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCatatActionPerformed
        // TODO add your handling code here:

        Pencatatan catat = null;
        try {
            catat = new Pencatatan();
            catat.setVisible(true);
            Beranda.this.setVisible(false);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Error : " + ex.getMessage());
        }

        //memunculkan jendela pencatatan jika memiliki limit bulanan
        int input;
        if (Main.limitBulananFinal <= 0) {
            input = JOptionPane.showConfirmDialog(null, "Anda tidak memiliki limit bulanan. Apakah anda ingin mengatur limit bulanan sekarang?\n"
                    + "Jika Ya tekan 'YES', jika Tidak tekan 'NO'", "Peringatan", JOptionPane.YES_NO_OPTION);
            if (input == 0) {
                Beranda.this.setVisible(false);
                catat.setVisible(false);
                try {
                    new Pengaturan().setVisible(true);
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Error : " + ex.getMessage());
                }

            } else {
                Beranda.this.setVisible(true);
                catat.setVisible(false);
            }
        }

    }//GEN-LAST:event_menuCatatActionPerformed

    //method tombol menu item untuk manampilkan pengaturan limit bulanan
    private void menuPengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPengaturanActionPerformed
        // TODO add your handling code here:
        
        try {
            Pengaturan atur = new Pengaturan();
            Beranda.this.setVisible(false);
            atur.setVisible(true);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Error : " + ex.getMessage());
        }
        
    }//GEN-LAST:event_menuPengaturanActionPerformed

    //method untuk menampilkan ke beranda
    private void menuBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBerandaActionPerformed
        // TODO add your handling code here:
        Beranda mainMenu;
        try {
            mainMenu = new Beranda();
            Beranda.this.setVisible(false);
            mainMenu.setVisible(true);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Error : " + ex.getMessage());
        }

    }//GEN-LAST:event_menuBerandaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem menuBeranda;
    private javax.swing.JMenuItem menuCatat;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenuItem menuLaporan;
    private javax.swing.JMenuItem menuPengaturan;
    // End of variables declaration//GEN-END:variables
}
