/**
 * Kelompok 10
 * Kelas    : S1 IF-06-B
 * Anggota  :
 * 1. Naufal Yusuf Kartiko (181020)
 * 2. Nur Rizki Adi Prasetyo (18102064)
 * 3. Wisanti (181020)
 */
package com.nurrizkiadip;

import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import java.text.ParseException;
import java.util.Date;

public class Pencatatan extends javax.swing.JFrame {

    private String tanggal; //menampungkan tanggal belanja pada data yang telah diklik user
    private String nama_toko; //menampungkan nama_toko saat belanja pada data yang telah diklik user
    private String nama_barang; //menampungkan nama barang saat belanja pada data yang telah diklik user
    private String jml_barang; //menampungkan jumlah belanja pada data yang telah diklik user
    private String hargaBarang; //menampungkan harga barang belanja pada data yang telah diklik user

    //method untuk mengkosongkan text field
    private void kosongkanForm() {
        tfNamaToko.setEditable(true);
        dateTanggal.setDate(null);
        tfNamaToko.setText(null);
        tfNamaBarang.setText(null);
        tfJmlBarang.setText(null);
        tfHargaBarang.setText(null);
    }

    public Pencatatan() throws ParseException {
        initComponents();
        tfSisaLimitBulanan.setText(String.valueOf(Main.limitBulananNonFinal));
        
        if (Main.waktuSetLimit != null) {
            Main.setUlangLimitBulanan();
        }
        tblStruk.setModel(Main.tampilkanDataTable());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNamaToko = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNamaBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dateTanggal = new com.toedter.calendar.JDateChooser();
        tfHargaBarang = new javax.swing.JTextField();
        btnBeranda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStruk = new javax.swing.JTable();
        btnTambahData = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfJmlBarang = new javax.swing.JTextField();
        tfSisaLimitBulanan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuBeranda = new javax.swing.JMenuItem();
        menuCatat = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenuItem();
        menuPengaturan = new javax.swing.JMenuItem();
        MenuEdit = new javax.swing.JMenu();
        menuKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pencatatan Struk Harian");
        setName("fCatat"); // NOI18N
        setSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 21)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Catat Pengeluaran");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Nama Toko");

        jLabel3.setText("Nama Barang");

        jLabel4.setText("Jumlah Barang");

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/SAVE-converted.png"))); // NOI18N
        btnSimpan.setText("  Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel5.setText("Tanggal");

        dateTanggal.setDateFormatString("yyyy-MM-dd");

        btnBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/homeflat_converted.png"))); // NOI18N
        btnBeranda.setText("  Beranda");
        btnBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerandaActionPerformed(evt);
            }
        });

        tblStruk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStruk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStrukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStruk);

        btnTambahData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-converted.png"))); // NOI18N
        btnTambahData.setText("  Tambah Data");
        btnTambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDataActionPerformed(evt);
            }
        });

        jLabel7.setText("Harga Barang");

        jLabel6.setText("Sisa Limit Bulanan");

        menuFile.setText("File");

        menuBeranda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/homeflat_converted2.png"))); // NOI18N
        menuBeranda.setText("Beranda");
        menuBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBerandaActionPerformed(evt);
            }
        });
        menuFile.add(menuBeranda);

        menuCatat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuCatat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/document_write_converted.png"))); // NOI18N
        menuCatat.setText("Catat Pengeluaran");
        menuCatat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCatatActionPerformed(evt);
            }
        });
        menuFile.add(menuCatat);

        menuLaporan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Laporan-converted2.png"))); // NOI18N
        menuLaporan.setText("Laporan");
        menuLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanActionPerformed(evt);
            }
        });
        menuFile.add(menuLaporan);

        menuPengaturan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuPengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Setting-converted2.png"))); // NOI18N
        menuPengaturan.setText("Pengaturan");
        menuPengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPengaturanActionPerformed(evt);
            }
        });
        menuFile.add(menuPengaturan);

        MenuBar.add(menuFile);

        MenuEdit.setText("Exit");

        menuKeluar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit-converted2.png"))); // NOI18N
        menuKeluar.setText("Keluar");
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        MenuEdit.add(menuKeluar);

        MenuBar.add(MenuEdit);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfHargaBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNamaToko, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfJmlBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel6)
                            .addComponent(tfSisaLimitBulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(btnBeranda)
                .addGap(18, 18, 18)
                .addComponent(btnTambahData)
                .addGap(18, 18, 18)
                .addComponent(btnSimpan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(dateTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNamaToko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfJmlBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSisaLimitBulanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBeranda)
                    .addComponent(btnTambahData)
                    .addComponent(btnSimpan))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBeranda, btnSimpan, btnTambahData});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //method tombol simpan untuk menyimpan perbelanjaan yang dimasukkan
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        String d = sdf.format(dateTanggal.getDate());

        String sql = "INSERT INTO db_strukharian.daftarbelanja VALUES('"
                + d + "','" + tfNamaToko.getText() + "','" + tfNamaBarang.getText() + "','"
                + tfJmlBarang.getText() + "','" 
                + tfHargaBarang.getText() + "','" 
                + Integer.parseInt(tfHargaBarang.getText())*Integer.parseInt(tfJmlBarang.getText()) + "')";
        String pesan;

        try {

            Connection conn = Database.koneksi();
            PreparedStatement pStt = conn.prepareStatement(sql);

            if (Integer.parseInt(tfHargaBarang.getText()) <= Main.limitBulananNonFinal) {
                if (Integer.parseInt(tfJmlBarang.getText()) >= 0) {
                    pStt.execute();

                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan...");
                    tblStruk.setModel(Main.tampilkanDataTable());

                    Main.limitBulananNonFinal = Main.limitBulananFinal - (Main.totalBelanja()-Main.totalBelanjaLama);

                    //=====  Pemasukkan data pengaturan yang terbaru =====
                    String sqlReset = "TRUNCATE TABLE db_strukharian.pengaturan";
                    conn = Database.koneksi();
                    pStt = conn.prepareStatement(sqlReset);
                    pStt.execute();
                    sql = "INSERT INTO pengaturan VALUES('" + Main.limitBulananFinal + "','" + Main.limitBulananNonFinal
                            + "','" + Main.pengingatLimitBulanan + "','" + Main.waktuSetLimit + "')";
                    pStt = conn.prepareStatement(sql);
                    pStt.execute();
                    //===== Akhir Pemasukkan data pengaturan yang terbaru =====

                    if (Main.limitBulananNonFinal < Main.pengingatLimitBulanan) {
                        pesan = "Anda mendekati batas limit bulanan. Sisa limit bulanan anda sebesar " + Main.limitBulananNonFinal;
                        JOptionPane.showMessageDialog(null, pesan, "WARNING", JOptionPane.WARNING_MESSAGE);
                    } else {
                        pesan = "Total belanja anda pada bulan ini sebesar " + String.valueOf(Main.totalBelanja()-Main.totalBelanjaLama) + ". Sisa saldo belanja anda sebesar " + Main.limitBulananNonFinal;
                        JOptionPane.showMessageDialog(null, pesan);
                    }
                } else {
                    pesan = "Anda mengisi angka negatif pada kolom jumlah barang";
                    JOptionPane.showMessageDialog(null, pesan, "WARNING", JOptionPane.WARNING_MESSAGE);
                }

            } else if (Main.limitBulananNonFinal == 0) {
                pesan = "Anda sudah berada pada batas limit bulanan." + Main.limitBulananNonFinal
                        + "\nAnda tidak bisa menambah barang belanja lagi. Mohon tunggu gajian dulu. Terimakasih.";
                JOptionPane.showMessageDialog(null, pesan, "WARNING", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Maaf, Biaya belanja melebihi limit bulanan anda\nLimit bulanan anda saat ini sebesar Rp " + Main.limitBulananNonFinal);
            }
            
            tfSisaLimitBulanan.setText(String.valueOf(Main.limitBulananNonFinal));
        } catch (SQLException | NumberFormatException  e) {
            JOptionPane.showMessageDialog(null, "Kesalahan pada simpan data\nError : " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }

        kosongkanForm();
    }//GEN-LAST:event_btnSimpanActionPerformed

    //method tombol beranda untuk kembali ke beranda
    private void btnBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerandaActionPerformed
        // TODO add your handling code here:
        Beranda mainMenu;
        try {
            mainMenu = new Beranda();
            mainMenu.setVisible(true);

            Pencatatan.this.setVisible(false);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Kesalahan pada menuju ke beranda\nError : " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnBerandaActionPerformed

    //method untuk memasukkan data belanja ke text field
    private void tblStrukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStrukMouseClicked
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        int baris = tblStruk.rowAtPoint(evt.getPoint());

        tanggal = tblStruk.getValueAt(baris, 1).toString();
        try {
            Date date = sdf.parse(tanggal);
            dateTanggal.setDate(date);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Kesalahan pada set tanggal saat data diklik\nError : " + e.getMessage(),
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
        
        nama_toko = tblStruk.getValueAt(baris, 2).toString();
        tfNamaToko.setText(nama_toko);

        nama_barang = tblStruk.getValueAt(baris, 3).toString();
        tfNamaBarang.setText(nama_barang);

        jml_barang = tblStruk.getValueAt(baris, 4).toString();
        tfJmlBarang.setText(jml_barang);

        hargaBarang = tblStruk.getValueAt(baris, 5).toString();
        tfHargaBarang.setText(hargaBarang);

    }//GEN-LAST:event_tblStrukMouseClicked

    //method tombol tambah untuk mengkosongkan text field
    private void btnTambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDataActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_btnTambahDataActionPerformed

    //method menu item beranda untuk menuju beranda
    private void menuBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBerandaActionPerformed
        // TODO add your handling code here:
        Beranda mainMenu;
        try {
            mainMenu = new Beranda();
            Pencatatan.this.setVisible(false);
            mainMenu.setVisible(true);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Kesalahan pada menuju ke beranda\nError : " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuBerandaActionPerformed

    //method menu item catat untuk menuju pencatatan belanja
    private void menuCatatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCatatActionPerformed
        // TODO add your handling code here:

        Pencatatan catat = null;
        try {
            catat = new Pencatatan();
            catat.setVisible(true);
            Pencatatan.this.setVisible(false);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Kesalahan menampilkan jendela pencatatan perbelanjaan\nError : " + ex.getMessage());
        }

    }//GEN-LAST:event_menuCatatActionPerformed

    //method menu item laporan untuk menuju laporan belanja
    private void menuLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanActionPerformed
        // TODO add your handling code here:
        Laporan lap = null;
        try {
            lap = new Laporan();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Kesalahan menampilkan laporan\nError : " + ex.getMessage());
        }
        Pencatatan.this.setVisible(false);
        lap.setVisible(true);
    }//GEN-LAST:event_menuLaporanActionPerformed

    //method menu item pengaturan untuk menuju pengaturan belanja
    private void menuPengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPengaturanActionPerformed
        // TODO add your handling code here:

        try {
            Pengaturan atur = new Pengaturan();
            Pencatatan.this.setVisible(false);
            atur.setVisible(true);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Kesalahan menampilkan pengaturan\nError : " + ex.getMessage());
        }

    }//GEN-LAST:event_menuPengaturanActionPerformed

    //method menu item keluar untuk mengakhiri running program
    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuKeluarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuEdit;
    private javax.swing.JButton btnBeranda;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahData;
    private com.toedter.calendar.JDateChooser dateTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuBeranda;
    private javax.swing.JMenuItem menuCatat;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenuItem menuLaporan;
    private javax.swing.JMenuItem menuPengaturan;
    private javax.swing.JTable tblStruk;
    private javax.swing.JTextField tfHargaBarang;
    private javax.swing.JTextField tfJmlBarang;
    private javax.swing.JTextField tfNamaBarang;
    private javax.swing.JTextField tfNamaToko;
    private javax.swing.JTextField tfSisaLimitBulanan;
    // End of variables declaration//GEN-END:variables
}
