/**
 * Kelompok 10
 * Kelas    : S1 IF-06-B
 * Anggota  :
 * 1. Naufal Yusuf Kartiko (181020)
 * 2. Nur Rizki Adi Prasetyo (18102064)
 * 3. Wisanti (181020)
 */
package com.nurrizkiadip;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

public class UbahDataBelanja extends javax.swing.JFrame {

    private String tanggal; //menampungkan tanggal belanja pada data yang telah diklik user
    private String nama_toko; //menampungkan nama_toko saat belanja pada data yang telah diklik user
    private String nama_barang; //menampungkan nama barang saat belanja pada data yang telah diklik user
    private String jml_barang; //menampungkan jumlah belanja pada data yang telah diklik user
    private String hargaBarang; //menampungkan harga barang belanja pada data yang telah diklik user

    /**
     * Konstruktor untuk mengisialisasi nilai atribut
     */
    public UbahDataBelanja(String tanggal, String nama_toko,
            String nama_barang, String jml_barang, String hargaBarang) {
        initComponents();
        this.tanggal = tanggal;
        this.nama_toko = nama_toko;
        this.nama_barang = nama_barang;
        this.jml_barang = jml_barang;
        this.hargaBarang = hargaBarang;
        
        setDataTableMouseClicked();
    }

    //method untuk memberikan data pada textfield berdasarkan data tabel yang di klik user
    public void setDataTableMouseClicked() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        try {
            Date date = sdf.parse(tanggal);
            dateTanggal.setDate(date);
            tfNamaToko.setText(nama_toko);
            tfNamaBarang.setText(nama_barang);
            tfJmlBarang.setText(jml_barang);
            tfHargaBarang.setText(hargaBarang);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Kesalahan pada set tanggal saat data diklik\nError : " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tfNamaToko = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNamaBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateTanggal = new com.toedter.calendar.JDateChooser();
        tfHargaBarang = new javax.swing.JTextField();
        btnUbah = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfJmlBarang = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ubah Data Struk Harian");
        setSize(new java.awt.Dimension(450, 350));

        jLabel2.setText("Nama Toko");

        jLabel3.setText("Nama Barang");

        jLabel4.setText("Jumlah Barang");

        jLabel5.setText("Tanggal");

        dateTanggal.setDateFormatString("yyyy-MM-dd");

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-converted.png"))); // NOI18N
        btnUbah.setText(" Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        jLabel7.setText("Harga Barang");

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_cancel_converted.png"))); // NOI18N
        btnBatal.setText("  Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 21)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ubah Data");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfHargaBarang, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfNamaBarang)
                    .addComponent(dateTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNamaToko)
                    .addComponent(tfJmlBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(dateTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNamaToko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfJmlBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //method tombol ubah untuk mengubah data pada table belanja
    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        String d = sdf.format(dateTanggal.getDate());

        String sql = "UPDATE db_strukharian.daftarbelanja SET tanggal='" + d + "', nama_toko='"
                + tfNamaToko.getText() + "', nama_barang='" + tfNamaBarang.getText() + "', jml_barang='"
                + tfJmlBarang.getText() + "', hargabarang='" + tfHargaBarang.getText()
                + "', totalhargabarang='" + Integer.parseInt(tfHargaBarang.getText()) * Integer.parseInt(tfJmlBarang.getText())
                + "' WHERE tanggal = '" + tanggal + "' AND nama_toko = '" + nama_toko + "' AND nama_barang='"
                + nama_barang + "' AND jml_barang='" + jml_barang
                + "' AND hargabarang='" + hargaBarang
                + "' AND totalhargabarang='" + Integer.parseInt(hargaBarang) * Integer.parseInt(jml_barang) + "'";

        String pesan;
        int harga_barang2 = Integer.parseInt(tfHargaBarang.getText()) * Integer.parseInt(tfJmlBarang.getText());

        try {
            Connection conn = Database.koneksi();

            String sql2 = "SELECT * FROM daftarbelanja WHERE tanggal = '" + tanggal
                    + "' AND nama_toko = '" + nama_toko + "' AND nama_barang='" + nama_barang
                    + "' AND jml_barang='" + jml_barang
                    + "' AND hargabarang='" + hargaBarang
                    + "' AND totalhargabarang='" + Integer.parseInt(hargaBarang) * Integer.parseInt(jml_barang) + "'";
            Statement stt = conn.createStatement();
            ResultSet resultSet = stt.executeQuery(sql2);
            resultSet.next();

            if (Integer.parseInt(resultSet.getString(5)) > harga_barang2) {
                harga_barang2 = Integer.parseInt(resultSet.getString(5)) - harga_barang2;
            } else if (Integer.parseInt(resultSet.getString(5)) < harga_barang2) {
                harga_barang2 = harga_barang2 - Integer.parseInt(resultSet.getString(5));
            }
            Main.limitBulananNonFinal = Integer.parseInt(hargaBarang);

            if (harga_barang2 <= Main.limitBulananNonFinal) {
                if (Integer.parseInt(tfJmlBarang.getText()) >= 0) {
                    PreparedStatement pStt = conn.prepareStatement(sql);
                    pStt.execute();

                    JOptionPane.showMessageDialog(null, "Data berhasil diubah...");

                    Main.limitBulananNonFinal = Main.limitBulananFinal - (Main.totalBelanja() - Main.totalBelanjaLama);

                    //=====  Pemasukkan data pengaturan yang terbaru =====
                    String sqlReset = "TRUNCATE TABLE db_strukharian.pengaturan";
                    conn = Database.koneksi();
                    pStt = conn.prepareStatement(sqlReset);
                    pStt.execute();
                    sql = "INSERT INTO pengaturan VALUES('" + Main.limitBulananFinal + "','" + Main.limitBulananNonFinal
                            + "','" + Main.pengingatLimitBulanan + "','" + Main.waktuSetLimit + "')";
                    pStt = conn.prepareStatement(sql);
                    pStt.execute();
                    //===== Akhir Pemasukkan data pengaturan yang terbaru =====

                    if (Main.limitBulananNonFinal <= Main.pengingatLimitBulanan) {
                        pesan = "Anda mendekati batas limit bulanan. Sisa limit bulanan anda sebesar " + Main.limitBulananNonFinal
                                + "\nTotal belanja anda pada bulan ini sebesar " + String.valueOf(Main.totalBelanja() - Main.totalBelanjaLama);
                        JOptionPane.showMessageDialog(null, pesan, "WARNING", JOptionPane.WARNING_MESSAGE);
                    } else if (Main.limitBulananNonFinal == 0) {
                        pesan = "Anda sudah berada pada batas limit bulanan." + Main.limitBulananNonFinal
                                + "\nAnda tidak bisa menambah barang belanja lagi. Mohon tunggu gajian dulu. Terimakasih.";
                        JOptionPane.showMessageDialog(null, pesan, "WARNING", JOptionPane.WARNING_MESSAGE);
                    } else {
                        pesan = "Total belanja anda pada bulan ini sebesar " + String.valueOf(Main.totalBelanja() - Main.totalBelanjaLama)
                                + ". Sisa saldo belanja anda sebesar " + Main.limitBulananNonFinal;
                        JOptionPane.showMessageDialog(null, pesan);
                    }
                } else {
                    pesan = "Maaf, anda mengisi angka negatif pada kolom jumlah barang";
                    JOptionPane.showMessageDialog(null, pesan, "WARNING", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Maaf, Biaya belanja melebihi limit bulanan anda\nLimit bulanan anda saat ini sebesar Rp " + Main.limitBulananNonFinal);

            }

            new Laporan().setVisible(false);
            new Laporan().setVisible(true);
            UbahDataBelanja.this.setVisible(false);
        } catch (SQLException | ParseException e) {
            JOptionPane.showMessageDialog(null, "Kesalahan pada ubah data\nError : " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnUbahActionPerformed

    //method tombol batal untuk membatalkan perubahan data belanja
    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        UbahDataBelanja.this.setVisible(false);

    }//GEN-LAST:event_btnBatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnUbah;
    private com.toedter.calendar.JDateChooser dateTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfHargaBarang;
    private javax.swing.JTextField tfJmlBarang;
    private javax.swing.JTextField tfNamaBarang;
    private javax.swing.JTextField tfNamaToko;
    // End of variables declaration//GEN-END:variables
}
